DRR - Cpptraj: Enable full clang diagnostics by default.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -252,6 +252,17 @@ while [[ ! -z $1 ]] ; do
       FOPTFLAGS="-O3"
       FLIBS="$FLIBS -lgfortran -w"
       ;;
+   "clang" )
+      echo "Using clang/gfortran compilers"
+      CC=clang
+      CXX=clang++
+      FC=gfortran
+      OPTFLAGS="-O3 -Weverything"
+      OMPFLAGS=""
+      FFLAGS="-ffree-form"
+      FOPTFLAGS="-O3"
+      FLIBS="$FLIBS -lgfortran -w"
+      ;; 
     "intel" )
       echo "Using intel compilers"
       CC=icc
@@ -542,6 +553,10 @@ fi
 
 # Add flags for OPENMP if specified
 if [[ $USEOPENMP -eq 1 ]] ; then
+  if [[ $CC = "clang" ]] ; then
+    echo "Error: clang compiler does not yet support OpenMP."
+    exit 1
+  fi
   echo "Using OPENMP"
   DIRECTIVES="$OMPFLAGS $DIRECTIVES"
   LDFLAGS="$OMPFLAGS $LDFLAGS"
