DRR - Cpptraj: Detect when CXX does not match specified compilers to avoid compile issues.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -830,17 +830,21 @@ SetupCompilers() {
   if [ ! -z "$CC"  ] ; then echo "C compiler (CC) set to $CC" ; fi
   if [ ! -z "$FC"  ] ; then echo "Fortran compiler (FC) set to $FC" ; fi
   # If no compiler type specified try to guess
-  if [ -z "$COMPILERS" ] ; then
-    if [ ! -z "$CXX" ] ; then
-      echo "Determining compilers from CXX ($CXX)"
-      case "$CXX" in
-        *g++*     ) COMPILERS='gnu' ;;
-        *clang++* ) COMPILERS='clang' ;;
-        *icpc*    ) COMPILERS='intel' ;;
-        *pgc++*   ) COMPILERS='pgi' ;;
-        *CC*      ) COMPILERS='cray' ;;
-        * ) echo "Warning: Could not detect compiler type ($CXX); assuming GNU" > /dev/stderr;;
-      esac
+  if [ -z "$COMPILERS" -o ! -z "$CXX" ] ; then
+    echo "Determining compilers from CXX ($CXX)"
+    SPECIFIED_COMPILER=$COMPILERS
+    case "$CXX" in
+      *g++*     ) COMPILERS='gnu' ;;
+      *clang++* ) COMPILERS='clang' ;;
+      *icpc*    ) COMPILERS='intel' ;;
+      *pgc++*   ) COMPILERS='pgi' ;;
+      *CC*      ) COMPILERS='cray' ;;
+      * ) echo "Warning: Could not detect compiler type ($CXX); assuming GNU" > /dev/stderr;;
+    esac
+    # If compiler was also specified make sure it matches as a sanity check
+    if [ ! -z "$SPECIFIED_COMPILER" -a "$SPECIFIED_COMPILER" != "$COMPILERS" ] ; then
+      echo "Error: $SPECIFIED_COMPILER compilers specified but need $COMPILERS based on CXX = $CXX" > /dev/stderr
+      exit 1
     fi
   fi
   # If still no compiler default to gnu
