DRR - Cpptraj: Fix up parsing of <var>=<value> args so that quoted <value> is processed properly. Use values of certain environment variables (e.g. CXX, CXXFLAGS) if they are set. Determine compilers from CXX if set and compilers not specified - default to gnu.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -57,16 +57,6 @@ UsageFull() {
   echo ""
 }
 
-# If arg is Key=Value, separate into Key and Value
-ParseArg() {
-  KEY=`echo "$1" | awk 'BEGIN{FS = "=";}{print $1;}'`
-  VALUE=`echo "$1" | awk 'BEGIN{FS = "=";}{print $2;}'`
-  eval VALUE=$VALUE
-  if [[ $VALUE = $KEY ]] ; then
-    VALUE=""
-  fi
-}
-
 # CompileError "Compile Line"
 # Compile error message
 CompileError() {
@@ -140,6 +130,7 @@ extern "C" {
 int main() {
   int n_cols = 3, lwork = 102, info;
   double work[102], mat[9], vec[3], alpha = 1.0;
+  mat[0] = 1.0; mat[4] = 1.0; mat[8] = 1.0;
   dsyev_((char*)"V", (char*)"U", n_cols, mat, n_cols, vec, work, lwork, info);
   dgemm_((char*)"N",(char*)"N", n_cols, n_cols, n_cols, alpha,
          mat, n_cols, mat, n_cols, alpha, mat, n_cols);
@@ -238,84 +229,10 @@ EOF
   fi
 }
 
-#---------------------------------------------------------------------
-
-if [[ -z $1  || $1 = "--help"  || $1 = "-h" ]] ; then
-  UsageSimple
-  exit 0
-elif [[ ! -z $1 && $1 = "--full-help" ]] ; then
-  UsageSimple
-  UsageFull
-  exit 0
-fi
-
-CONFIGURECMD="./configure $*"
-
-KEY=""
-VALUE=""
-echo ""
-
-# System env variables
-CC=""
-CXX=""
-FC=""
-CFLAGS=""
-CXXFLAGS=""
-FFLAGS=""
-LDFLAGS=""
-
-# Process Options
-ARCHITECTURE="x86_64" # TODO: Actually determine
-OPT=1
-USEMPI=0
-USEOPENMP=0
-USETIMER=0
-PROFILE=0
-USECRAY=0
-USESHARED=0
-SFX=""
-CPPTRAJHOME=""
-CPPTRAJBIN=""
-CPPTRAJLIB=""
-DIRECTIVES=""
-DBGFLAGS=""
-OPTFLAGS=""
-OMPFLAGS=""
-FOPTFLAGS=""
-PICFLAG=""
-LFS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
-INCLUDE=""
-# Library flags
-STATIC=0
-NETCDF_HOME=""
-PNETCDF_HOME=""
-BZLIB_HOME=""
-ZLIB_HOME=""
-BLAS_HOME=""
-LAPACK_HOME=""
-ARPACK_HOME=""
-READLINE_HOME="readline"
-NETCDFLIB="-lnetcdf"
-PNETCDFLIB=""
-BZLIB="-lbz2"
-ZLIB="-lz"
-BLAS="-lblas"
-LAPACK="-llapack"
-ARPACK="-larpack"
-FFT_LIB="pub_fft.o"
-FFT_LIBDIR=""
-FFT_DEPEND=$FFT_LIB
-LIBCPPTRAJ="nolibcpptraj" # Set to libcpptraj.so if library will be built
-SANDERLIB=""
-READLINE=$READLINE_HOME/libreadline.a
-USE_AMBER_LIB=0
-USEMKL=0
-FLIBS=""
-#HDF5LIB="-lhdf5_hl -lhdf5"
-HDF5LIB=""
-while [[ ! -z $1 ]] ; do
-  ParseArg $1
-  case "$KEY" in
+#-------------------------------------------------------------------------------
+# Usage: SetCompilerOptions <compilers>
+SetCompilerOptions() {
+  case "$1" in
     "gnu" )
       echo "Using gnu compilers"
       CC=gcc
@@ -377,17 +294,135 @@ while [[ ! -z $1 ]] ; do
       FLIBS=""
       PICFLAG="-fpic"
       ;;
+    * ) echo "Error: Unknown compilers: $1" > /dev/stderr ; exit 1 ;;
+  esac
+}
+
+#-------------------------------------------------------------------------------
+# Check if first arg is help arg
+if [[ $1 = "--help"  || $1 = "-h" ]] ; then
+  UsageSimple
+  exit 0
+elif [[ $1 = "--full-help" ]] ; then
+  UsageSimple
+  UsageFull
+  exit 0
+fi
+
+CONFIGURECMD="./configure $*"
+
+echo ""
+
+# Determine architecture
+ARCHITECTURE=`uname -m`
+if [[ "$ARCHITECTURE" = "x86_64" || "$ARCHITECTURE" = "em64t" ]] ; then
+  IS_64BIT=1
+  echo "Assuming 64 bit architecture."
+else
+  IS_64BIT=0
+  echo "Assuming 32 bit architecture."
+fi
+
+# System env variables. Do not clear these yet.
+#CC="" #CXX="" #FC=""
+#CFLAGS="" #CXXFLAGS="" #FFLAGS="" #LDFLAGS=""
+#DBGFLAGS=""
+# Configure Options
+COMPILERS=""
+OPT=1
+USEMPI=0
+USEOPENMP=0
+USETIMER=0
+PROFILE=0
+USECRAY=0
+USESHARED=0
+SFX=""
+CPPTRAJHOME=""
+CPPTRAJBIN=""
+CPPTRAJLIB=""
+DIRECTIVES=""
+DEBUGFLAGS=""
+OPTFLAGS=""
+OMPFLAGS=""
+FOPTFLAGS=""
+PICFLAG=""
+LFS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
+INCLUDE=""
+# Library flags
+STATIC=0
+NETCDF_HOME=""
+PNETCDF_HOME=""
+BZLIB_HOME=""
+ZLIB_HOME=""
+BLAS_HOME=""
+LAPACK_HOME=""
+ARPACK_HOME=""
+READLINE_HOME="readline"
+NETCDFLIB="-lnetcdf"
+PNETCDFLIB=""
+BZLIB="-lbz2"
+ZLIB="-lz"
+BLAS="-lblas"
+LAPACK="-llapack"
+ARPACK="-larpack"
+FFT_LIB="pub_fft.o"
+FFT_LIBDIR=""
+FFT_DEPEND=$FFT_LIB
+LIBCPPTRAJ="nolibcpptraj" # Set to libcpptraj.so if library will be built
+SANDERLIB=""
+READLINE=$READLINE_HOME/libreadline.a
+USE_AMBER_LIB=0
+USEMKL=0
+FLIBS=""
+HDF5LIB="" #"-lhdf5_hl -lhdf5"
+
+# Parse command line options
+KEY=""
+VALUE=""
+while [[ ! -z $1 ]] ; do
+  # If arg is Key=Value, separate into Key and Value
+  VALUE=""
+  POS=`expr index "$1" '='`
+  if [[ $POS -eq 1 ]] ; then
+    echo "Error: '=' cannot be first character in an argument." > /dev/stderr ; exit 1
+  elif [[ $POS -gt 1 ]] ; then
+    ((PM1 = $POS - 1))
+    KEY=${1:0:$PM1}
+    VALUE=${1:$POS}
+    if [[ $VALUE = "" ]] ; then
+      echo "Error: '$1': Expected <var>=<value>, missing <value>." > /dev/stderr ; exit 1
+    fi
+    eval VALUE=$VALUE 2> /dev/null
+  else
+    KEY=$1
+  fi
+  #echo "KEY='$KEY',  VALUE='$VALUE'" #DEBUG
+  # Process KEY
+  case "$KEY" in
+    "gnu"   ) COMPILERS=$KEY ;;
+    "clang" ) COMPILERS=$KEY ;;
+    "intel" ) COMPILERS=$KEY ;;
+    "pgi"   ) COMPILERS=$KEY ;;
+    "cray"  ) COMPILERS=$KEY ;;
+    "CXX"   ) CXX="$VALUE" ;;
+    "CC"    ) echo "Warning: CC set but not used (use CXX to determine compilers)." ;;
+    "FC"    ) echo "Warning: FC set but not used (use CXX to determine compilers)." ;;
+    "CXXFLAGS" ) CXXFLAGS="$VALUE" ;;
+    "CFLAGS"   ) CFLAGS="$VALUE" ;;
+    "FFLAGS"   ) FFLAGS="$VALUE" ;;
+    "LDFLAGS"  ) LDFLAGS="$VALUE" ;;
+    "DBGFLAGS" ) DBGFLAGS="$VALUE" ;;
     "-cray" )
       echo "Using cray compiler wrappers (cc/CC/ftn)"
       USECRAY=1
       ;;
     "-debug" )
       echo "Turning on compiler debug info"
-      DBGFLAGS="-g"
+      DEBUGFLAGS="-g"
       ;;
     "-d" )
       echo "Turning on compiler debug info and disabling optimization"
-      DBGFLAGS="-g"
+      DEBUGFLAGS="-g"
       OPT=0
       ;;
     "-debugon"      )
@@ -547,6 +582,36 @@ while [[ ! -z $1 ]] ; do
   shift
 done
 
+# If compiler has not yet been specified, determine from CXX, otherwise default
+# to GNU
+if [[ -z $COMPILERS ]] ; then
+  if [[ ! -z $CXX ]] ; then
+    echo "Determining compilers from CXX ($CXX)"
+    case "$CXX" in
+      "g++"     ) COMPILERS='gnu' ;;
+      "clang++" ) COMPILERS='clang' ;;
+      "icpc"    ) COMPILERS='intel' ;;
+      "pgc++"   ) COMPILERS='pgi' ;;
+      "CC"      ) COMPILERS='cray' ;;
+      * ) echo "Error: Unrecognized compiler: $CXX" > /dev/stderr ; exit 1 ;;
+    esac
+  else
+    COMPILERS='gnu'
+    echo "No compilers specified; defaulting to GNU."
+  fi
+else
+  # Compiler was specified on command line. Ignore flags from outside.
+  if [[ ! -z $CFLAGS || ! -z $CXXFLAGS || ! -z $FFLAGS || ! -z $LDFLAGS ]] ; then
+    echo "Warning: Compiler specified on command line. Ignoring CFLAGS, CXXFLAGS,"
+    echo "         FFLAGS, and LDFLAGS from environment/command line."
+  fi
+  CFLAGS=""
+  CXXFLAGS=""
+  FFLAGS=""
+  LDFLAGS=""
+fi
+SetCompilerOptions $COMPILERS
+
 # Check install directory
 if [[ -z $CPPTRAJHOME ]] ; then
   # Default is to use current directory.
@@ -673,7 +738,7 @@ fi
 MKLLIB=""
 if [[ $USEMKL -eq 1 ]] ; then
   # Use MKL for LAPACK/BLAS
-  if [[ $ARCHITECTURE = "x86_64" ]] ; then
+  if [[ $IS_64BIT -eq 1 ]] ; then
     MKLINTERFACE=libmkl_intel_lp64.a
     MKLROOT="$MKLROOT/lib/intel64"
     BLAS="-lmkl_blas95_lp64"
@@ -702,8 +767,10 @@ if [[ "$(uname)" == "Darwin" && "$FFT_LIB" == "-lfftw3" ]] ; then
     FLIBS=""
 fi
 
-# Set up linking flags
-LDFLAGS="$ARPACK $LAPACK $BLAS $MKLLIB $NETCDFLIB $PNETCDFLIB $BZLIB $ZLIB $FLIBS"
+# Set up linking flags if not already set
+if [[ -z $LDFLAGS ]] ; then
+  LDFLAGS="$ARPACK $LAPACK $BLAS $MKLLIB $NETCDFLIB $PNETCDFLIB $BZLIB $ZLIB $FLIBS"
+fi
 if [[ ! -z $FFT_LIBDIR ]] ; then
   FFT_LIB="$FFT_LIBDIR $FFT_LIB"
 fi
@@ -737,7 +804,7 @@ fi
 if [[ $OPT -eq 0 ]] ; then
   OPTFLAGS=""
   FOPTFLAGS=""
-  DBGFLAGS="$DBGFLAGS -O0"
+  DEBUGFLAGS="$DEBUGFLAGS -O0"
 fi
 
 # Add cray-specific flags
@@ -764,10 +831,16 @@ if [[ $USEMPI -eq 1 ]] ; then
   SFX=".MPI"
 fi
 
-# Set up compiler flags
-CFLAGS="$DBGFLAGS $OPTFLAGS $DIRECTIVES $LFS $INCLUDE"
-CXXFLAGS="$DBGFLAGS $OPTFLAGS $DIRECTIVES $LFS $INCLUDE"
-FFLAGS="$FFLAGS $DBGFLAGS $FOPTFLAGS $DIRECTIVES $LFS $INCLUDE"
+# Set up compiler flags if not already set
+if [[ -z $CFLAGS ]] ; then
+  CFLAGS="$DEBUGFLAGS $OPTFLAGS $DIRECTIVES $LFS $INCLUDE"
+fi
+if [[ -z $CXXFLAGS ]] ; then
+  CXXFLAGS="$DEBUGFLAGS $OPTFLAGS $DIRECTIVES $LFS $INCLUDE"
+fi
+if [[ -z $FFLAGS ]] ; then
+  FFLAGS="$FFLAGS $DEBUGFLAGS $FOPTFLAGS $DIRECTIVES $LFS $INCLUDE"
+fi
 
 # Add position-independent code if necessary
 if [[ $USESHARED -eq 1 ]] ; then
@@ -777,7 +850,7 @@ if [[ $USESHARED -eq 1 ]] ; then
 fi
 
 # Add debug flags for non-PGI compilers if debug info on
-if [[ ! -z $DBGFLAGS && $CXX != "pgc++" ]] ; then
+if [[ ! -z $DEBUGFLAGS && $CXX != "pgc++" ]] ; then
   CFLAGS="-Wall $CFLAGS"
   CXXFLAGS="-Wall -fno-inline $CXXFLAGS"
   FFLAGS="-Wall $FFLAGS"
@@ -828,7 +901,7 @@ CPPTRAJHOME=$CPPTRAJHOME
 CPPTRAJBIN=$CPPTRAJBIN
 CPPTRAJLIB=$CPPTRAJLIB
 
-DBGFLAGS=
+DBGFLAGS=$DBGFLAGS
 CC=$CC
 CXX=$CXX
 FC=$FC
