Fix up configure script and Makefile to work with cross-compiled windows build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27,6 +27,7 @@ UsageFull() {
   echo "    -nolfs     : Do not enable large file support."
   echo "    -shared    : Enable position-independent code for generating shared library."
   echo "    -fftw3     : Use FFTW instead of pubfft for FFT."
+  echo "    -windows   : Set up for use with MinGW compilers for a native Windows build"
   echo ""
   echo "  LIBRARY LINKING OPTIONS:"
   echo "    --with-netcdf=<DIR>"
@@ -37,18 +38,19 @@ UsageFull() {
   echo "    --with-arpack=<DIR>"
   echo "    --with-fftw3=<DIR>"
 #  echo "   --with-hdf5=<DIR>"
-  echo "    -static    : Use static linking."
-  echo "    -amberlib  : Use BLAS/ARPACK/LAPACK/NetCDF libraries from \$AMBERHOME"
-  echo "    -nobzlib   : Do not use libbz2 (bzip2)"
-  echo "    -nozlib    : Do not use zlib (gzip/zip)"
-  echo "    -nonetcdf  : Do not use NetCDF"
-  echo "    -nomathlib : Do not include routines which require LAPACK or BLAS"
-  echo "    -noarpack  : Do not include routines which require ARPACK"
+  echo "    -static     : Use static linking."
+  echo "    -amberlib   : Use BLAS/ARPACK/LAPACK/NetCDF libraries from \$AMBERHOME"
+  echo "    -nobzlib    : Do not use libbz2 (bzip2)"
+  echo "    -nozlib     : Do not use zlib (gzip/zip)"
+  echo "    -nonetcdf   : Do not use NetCDF"
+  echo "    -nomathlib  : Do not include routines which require LAPACK or BLAS"
+  echo "    -noarpack   : Do not include routines which require ARPACK"
+  echo "    -noreadline : Do not include support for readline in the interpreter"
   echo ""
   echo "  ENVIRONMENT VARIABLES (can also be passed to configure as <VAR>=<VALUE>):"
   echo "    CXX        : Name of the C++ compiler."
-  #echo "    CC         : Name of the C compiler."
-  #echo "    FC         : Name of the fortran compiler."
+  echo "    CC         : Name of the C compiler."
+  echo "    FC         : Name of the fortran compiler."
   echo "    CXXFLAGS   : Flags to pass to the C++ compiler."
   echo "    CFLAGS     : Flags to pass to the C compiler."
   echo "    FFLAGS     : Flags to pass to the Fortran compiler."
@@ -248,9 +250,9 @@ SetCompilerOptions() {
   case "$1" in
     "gnu" )
       echo "Using gnu compilers"
-      CC=gcc
-      CXX=g++
-      FC=gfortran
+      if [ -z "$CC" ]; then CC=gcc; fi
+      if [ -z "$CXX" ]; then CXX=g++; fi
+      if [ -z "$FC" ]; then FC=gfortran; fi
       OPTFLAGS="-O3 -Wall"
       OMPFLAGS="-fopenmp"
       FFLAGS="-ffree-form"
@@ -260,9 +262,9 @@ SetCompilerOptions() {
       ;;
    "clang" )
       echo "Using clang/gfortran compilers"
-      CC=clang
-      CXX=clang++
-      FC=gfortran
+      if [ -z "$CC" ]; then CC=clang; fi
+      if [ -z "$CXX" ]; then CXX=clang++; fi
+      if [ -z "$FC" ]; then FC=gfortran; fi
       OPTFLAGS="-O3 -Wall"
       OMPFLAGS=""
       FFLAGS="-ffree-form"
@@ -272,9 +274,9 @@ SetCompilerOptions() {
       ;;
     "intel" )
       echo "Using intel compilers"
-      CC=icc
-      CXX=icpc
-      FC=ifort
+      if [ -z "$CC" ]; then CC=icc; fi
+      if [ -z "$CXX" ]; then CXX=icpc; fi
+      if [ -z "$FC" ]; then FC=ifort; fi
       OPTFLAGS="-O3 -Wall"
       OMPFLAGS="-openmp"
       FFLAGS="-FR"
@@ -284,9 +286,9 @@ SetCompilerOptions() {
       ;;
     "pgi" )
       echo "Using PGI compilers"
-      CC=pgcc
-      CXX=pgc++
-      FC=pgf90
+      if [ -z "$CC" ]; then CC=pgcc; fi
+      if [ -z "$CXX" ]; then CXX=pgc++; fi
+      if [ -z "$FC" ]; then FC=pgf90; fi
       OPTFLAGS="-O2"
       OMPFLAGS="-mp"
       FFLAGS="-Mfree"
@@ -297,9 +299,9 @@ SetCompilerOptions() {
     "cray" )
       echo "Using Cray compilers"
       USECRAY=1
-      CC=cc
-      CXX=CC
-      FC=ftn
+      if [ -z "$CC" ]; then CC=cc; fi
+      if [ -z "$CXX" ]; then CXX=CC; fi
+      if [ -z "$FC" ]; then FC=ftn; fi
       OPTFLAGS="-h gnu"
       OMPFLAGS=""
       FFLAGS="-f free -emf"
@@ -363,7 +365,7 @@ LFS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
 INCLUDE=""
 # Library flags
 STATIC=0
-#STATICFLAG="-static"
+STATICFLAG="-static"
 NETCDF_HOME=""
 PNETCDF_HOME=""
 BZLIB_HOME=""
@@ -390,6 +392,8 @@ USE_AMBER_LIB=0
 USEMKL=0
 FLIBS=""
 HDF5LIB="" #"-lhdf5_hl -lhdf5"
+WINDOWS="no"
+CROSS_COMPILE="no"
 
 # Parse command line options
 KEY=""
@@ -420,8 +424,8 @@ while [[ ! -z $1 ]] ; do
     "pgi"   ) COMPILERS=$KEY ;;
     "cray"  ) COMPILERS=$KEY ;;
     "CXX"   ) CXX="$VALUE" ;;
-    "CC"    ) echo "Warning: CC set but not used (use CXX to determine compilers)." ;;
-    "FC"    ) echo "Warning: FC set but not used (use CXX to determine compilers)." ;;
+    "CC"    ) CC="$VALUE" ;;
+    "FC"    ) FC="$VALUE" ;;
     "CXXFLAGS" ) CXXFLAGS="$VALUE" ;;
     "CFLAGS"   ) CFLAGS="$VALUE" ;;
     "FFLAGS"   ) FFLAGS="$VALUE" ;;
@@ -536,6 +540,22 @@ while [[ ! -z $1 ]] ; do
       DIRECTIVES="$DIRECTIVES -DNO_ARPACK"
       ARPACK=""
       ;;
+    "-noreadline")
+      echo "Not using READLINE."
+      DIRECTIVES="$DIRECTIVES -DNO_READLINE"
+      READLINE_TARGET="noreadline"
+      READLINE=""
+      ;;
+    "-windows")
+      echo "WINDOWS support requested. Implies -static, -noreadline"
+      DIRECTIVES="$DIRECTIVES -DNO_READLINE"
+      READLINE_TARGET="noreadline"
+      READLINE=""
+      STATIC=1
+      WINDOWS="yes"
+      CROSS_COMPILE="yes" # TODO: Figure out a better way to detect
+      SFX=".exe"
+      ;;
     "--with-bzlib"  )
       INCLUDE="$INCLUDE -I$VALUE/include"
       BZLIB_HOME="$VALUE"
@@ -602,28 +622,19 @@ done
 if [[ -z $COMPILERS ]] ; then
   if [[ ! -z $CXX ]] ; then
     echo "Determining compilers from CXX ($CXX)"
+    COMPILERS='gnu'
     case "$CXX" in
       "g++"     ) COMPILERS='gnu' ;;
       "clang++" ) COMPILERS='clang' ;;
       "icpc"    ) COMPILERS='intel' ;;
       "pgc++"   ) COMPILERS='pgi' ;;
       "CC"      ) COMPILERS='cray' ;;
-      * ) echo "Error: Unrecognized compiler: $CXX" > /dev/stderr ; exit 1 ;;
+      * ) echo "Warning: Could not detect compiler type ($CXX); assuming gnu" > /dev/stderr;;
     esac
   else
     COMPILERS='gnu'
     echo "No compilers specified; defaulting to GNU."
   fi
-else
-  # Compiler was specified on command line. Ignore flags from outside.
-  if [[ ! -z $CFLAGS || ! -z $CXXFLAGS || ! -z $FFLAGS || ! -z $LDFLAGS ]] ; then
-    echo "Warning: Compiler specified on command line. Ignoring CFLAGS, CXXFLAGS,"
-    echo "         FFLAGS, and LDFLAGS from environment/command line."
-  fi
-  CFLAGS=""
-  CXXFLAGS=""
-  FFLAGS=""
-  LDFLAGS=""
 fi
 SetCompilerOptions $COMPILERS
 
@@ -782,9 +793,7 @@ if [[ "$(uname)" == "Darwin" && "$FFT_LIB" == "-lfftw3" ]] ; then
 fi
 
 # Set up linking flags if not already set
-if [[ -z $LDFLAGS ]] ; then
-  LDFLAGS="$ARPACK $LAPACK $BLAS $MKLLIB $NETCDFLIB $PNETCDFLIB $BZLIB $ZLIB $FLIBS"
-fi
+LDFLAGS="$ARPACK $LAPACK $BLAS $MKLLIB $NETCDFLIB $PNETCDFLIB $BZLIB $ZLIB $FLIBS $LDFLAGS"
 if [[ ! -z $FFT_LIBDIR ]] ; then
   FFT_LIB="$FFT_LIBDIR $FFT_LIB"
 fi
@@ -797,13 +806,17 @@ fi
 
 # For pgi on cray modify some flags
 if [[ $USECRAY -eq 1 && $COMPILERS = "pgi" ]] ; then
-    OPTFLAGS="-fast"
-    OMPFLAGS="-mp=nonuma"
-    FOPTFLAGS="-fast"
+  OPTFLAGS="-fast"
+  OMPFLAGS="-mp=nonuma"
+  FOPTFLAGS="-fast"
 fi
 
 # Add flags for OPENMP if specified
 if [[ $USEOPENMP -eq 1 ]] ; then
+  if [[ "$WINDOWS" = "yes" ]]; then
+    echo "OpenMP not currently supported on Windows"
+    exit 1
+  fi
   if [[ $COMPILERS = "clang" ]] ; then
     echo "Error: clang compiler does not yet support OpenMP."
     exit 1
@@ -834,6 +847,10 @@ fi
 
 # Change to MPI compiler wrappers if specified
 if [[ $USEMPI -eq 1 ]] ; then
+  if [[ "$WINDOWS" = "yes" ]]; then
+    echo "MPI not currently supported on Windows"
+    exit 1
+  fi
   echo "Using MPI"
   DIRECTIVES="$DIRECTIVES -DMPI"
   CC=mpicc
@@ -843,15 +860,9 @@ if [[ $USEMPI -eq 1 ]] ; then
 fi
 
 # Set up compiler flags if not already set
-if [[ -z $CFLAGS ]] ; then
-  CFLAGS="$DEBUGFLAGS $OPTFLAGS $DIRECTIVES $LFS $INCLUDE"
-fi
-if [[ -z $CXXFLAGS ]] ; then
-  CXXFLAGS="$DEBUGFLAGS $OPTFLAGS $DIRECTIVES $LFS $INCLUDE"
-fi
-if [[ -z $FFLAGS ]] ; then
-  FFLAGS="$FFLAGS $DEBUGFLAGS $FOPTFLAGS $DIRECTIVES $LFS $INCLUDE"
-fi
+CFLAGS="$DEBUGFLAGS $OPTFLAGS $DIRECTIVES $LFS $INCLUDE $CFLAGS"
+CXXFLAGS="$DEBUGFLAGS $OPTFLAGS $DIRECTIVES $LFS $INCLUDE $CXXFLAGS"
+FFLAGS="$DEBUGFLAGS $FOPTFLAGS $DIRECTIVES $LFS $INCLUDE $FFLAGS"
 
 # Add position-independent code if necessary
 if [[ $USESHARED -eq 1 ]] ; then
@@ -894,14 +905,21 @@ if [[ $USECRAY -eq 1 ]] ; then
   FC=ftn
 fi
 
-# Test compilers
-TestCompile
-TestBzlib
-TestZlib
-TestNetcdf
-TestMathlib
-TestArpack
-TestFFTW3
+# Set up static compilers
+if [[ $STATIC -eq 1 ]]; then
+  LDFLAGS="$LDFLAGS $STATICFLAG"
+fi
+
+# Test compilers (if we are not cross-compiling)
+if [[ "$CROSS_COMPILE" = "no" ]]; then
+  TestCompile
+  TestBzlib
+  TestZlib
+  TestNetcdf
+  TestMathlib
+  TestArpack
+  TestFFTW3
+fi
 
 # Write config.h
 cat > config.h <<EOF
