Add install of openblas

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -655,7 +655,34 @@ int main() {
 EOF
   DetermineFlink "  Checking LAPACK/BLAS" "${LIB_FLAG[$LLAPACK]} ${LIB_FLAG[$LBLAS]}"
   if [ $? -ne 0 ] ; then
-    TestProgErr "LAPACK/BLAS"
+    if [ "${LIB_STAT[$LBLAS]}" = 'enabled' ] ; then
+      # See if there is already a version of OpenBLAS in CPPTRAJHOME
+      LIB_STAT[$LBLAS]='specified'
+      LIB_HOME[$LBLAS]=$CPPTRAJHOME
+      LIB_FLAG[$LBLAS]=$CPPTRAJHOME/lib/libopenblas.a
+      LIB_INCL[$LBLAS]="-I$CPPTRAJHOME/include"
+      LIB_STAT[$LLAPACK]='off'
+      LIB_FLAG[$LLAPACK]=''
+      DetermineFlink "  Checking for bundled OpenBLAS" "${LIB_FLAG[$LLAPACK]} ${LIB_FLAG[$LBLAS]}"
+      #TestProgram silent "  Checking for bundled OpenBLAS" "$CXX" "$CXXFLAGS ${LIB_INCL[$LBLAS]}" testp.cpp "${LIB_FLAG[$LBLAS]}"
+      if [ $? -ne 0 ] ; then
+        # Check if lib present but needs to be rebuilt
+        CheckRebuild "OpenBLAS" "${LIB_FLAG[$LBLAS]}"
+        # See if user would like to get openblas
+        PREFIX=$CPPTRAJHOME CC=$CC CFLAGS=$CFLAGS LIBNAME='openblas' \
+            SRCDIR=$MATH_SRCDIR SRCTAR=$MATH_SRCTAR URL=$MATH_URL ./get_library.sh $REBUILDOPT $MATH_OPTS
+        if [ $? -ne 0 ] ; then
+          ErrMsg "Building OpenBLAS failed."
+          exit 1
+        fi
+        # Test the built openblas
+        DetermineFlink "  Checking built OpenBLAS" "${LIB_FLAG[$LLAPACK]} ${LIB_FLAG[$LBLAS]}"
+        #TestProgram "  Checking built OpenBLAS" "$CXX" "$CXXFLAGS ${LIB_INCL[$LBLAS]}" testp.cpp "${LIB_FLAG[$LBLAS]}"
+      fi
+    else
+      # BLAS specified but failed.
+      TestProgErr "LAPACK/BLAS"
+    fi
   fi
 }
 
