DRR - Cpptraj: Make '-sanderlib' option require external fft library. Since both libsander and cpptraj try to use pubfft but have slightly different implemenations, we get cross-pollination of symbols and bad things happen...

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -887,6 +887,10 @@ fi
 
 # Flags for libsander
 if [[ ! -z $SANDERLIB ]] ; then
+  if [[ ! -z $FFT_DEPEND ]] ; then
+    echo "Error: '-sanderlib' currently requires use of external FFT library ('-fftw3')."
+    exit 1
+  fi
   DIRECTIVES=$DIRECTIVES" -DUSE_SANDERLIB"
   LDFLAGS=$LDFLAGS" $SANDERLIB"
 fi
