DRR - Cpptraj: Add check to configure to see if flag needed for older MPI versions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1251,6 +1251,26 @@ if [[ $USEMPI -ne 0 ]] ; then
     CXX=mpiicpc
     FC=mpiifort
   fi
+  # Older Intel compilers have a problem with the order of stdio vs mpi
+  cat > testp.cpp <<EOF
+#include <cstdio>
+#include <mpi.h>
+int main() { printf("Testing a C++ MPI program.\n"); return 0; }
+EOF
+  $CXX -o testp testp.cpp > /dev/null 2> compile.err 
+  if [ "$?" -ne 0 ] ; then
+    # Try to fix with -DMPICH_IGNORE_CXX_SEEK
+    $CXX -o testp -DMPICH_IGNORE_CXX_SEEK testp.cpp > /dev/null 2> compile.err
+    if [ "$?" -eq 0 ] ; then
+      # That worked. Add to CXXFLAGS
+      CXXFLAGS="$CXXFLAGS -DMPICH_IGNORE_CXX_SEEK"
+    else
+      echo "Error: Could not compile an MPI program with $CXX." > /dev/stderr
+      cat compile.err
+      exit 1
+    fi
+  fi
+  rm -f testp.cpp testp compile.err
 fi
 
 # Set up compiler flags if not already set
